export const mockNotifications = [
  {
    read: false,
    title: "New Chat Message",
    description: "You’ve received a new message from Jane.",
    time: "2025-05-24T08:45:00Z",
    type: "new-chat",
  },
  {
    read: true,
    title: "Offer Accepted",
    description: "Your service offer was accepted by Daniel.",
    time: "2025-05-23T16:20:00Z",
    type: "offer-accepted",
  },
  {
    read: false,
    title: "New Review",
    description: "John left a review on your profile.",
    time: "2025-05-24T09:00:00Z",
    type: "new-review",
  },
  {
    read: true,
    title: "Offer Declined",
    description: "Your offer was declined by Sarah.",
    time: "2025-05-22T14:10:00Z",
    type: "offer-declined",
  },
  {
    read: false,
    title: "New Service Request",
    description: "You have a new service request from Mike.",
    time: "2025-05-24T07:30:00Z",
    type: "new-request",
  },
  {
    read: false,
    title: "New Chat Message",
    description: "Alex sent you a message.",
    time: "2025-05-24T10:15:00Z",
    type: "new-chat",
  },
  {
    read: true,
    title: "Offer Accepted",
    description: "Liam accepted your service offer.",
    time: "2025-05-21T11:00:00Z",
    type: "offer-accepted",
  },
  {
    read: false,
    title: "New Review",
    description: "Emma gave you a 5-star rating.",
    time: "2025-05-24T06:50:00Z",
    type: "new-review",
  },
  {
    read: true,
    title: "Offer Declined",
    description: "Michael declined your proposal.",
    time: "2025-05-20T18:25:00Z",
    type: "offer-declined",
  },
  {
    read: false,
    title: "New Service Request",
    description: "Chloe just submitted a new request.",
    time: "2025-05-24T09:40:00Z",
    type: "new-request",
  },
];

export const notifyType = [
  {
    title: "All Notifications",
    value: "all",
  },
  {
    title: "Unread",
    value: "unread",
  },
];

export const listingStatus = [
  {
    title: "All",
    value: "all",
  },
  {
    title: "Active",
    value: "active",
  },
  {
    title: "Pending",
    value: "pending",
  },
  {
    title: "Flagged",
    value: "flagged",
  },
  {
    title: "Completed",
    value: "completed",
  },
];

export const mockListings = [
  {
    date: "2025-07-21T10:30:00Z",
    name: "iPhone 14 Pro Max",
    condition: "Like New",
    price: 1200,
    itemUrl: "https://example.com/images/iphone14promax.png",
    category: "Electronics",
    status: "Completed",
    description: "A barely used iPhone 14 Pro Max, 512GB, Silver.",
    location: "Lagos, Nigeria",
    dateListed: "May 5, 2025",
    datePosted: "May 5, 2025",
    edited: "May 5, 2025",
    requestedInExchange: [{ name: "Samsung Galaxy S23 Ultra" }],
    owner: "Sarah Johnson",
    ownerAvatar: "https://example.com/images/avatar1.png",
    rating: 4.9,
    swap: { total: 10 },
  },
  {
    name: "Pending Verification",
    date: "2025-07-20T15:45:00Z",
    item: "Samsung Galaxy Z Fold 5",
    condition: "Brand New",
    price: 1500,
    itemUrl: "https://example.com/images/galaxyzfold5.png",
    category: "Electronics",
    status: "Pending",
    description: "Brand new Samsung Galaxy Z Fold 5, unopened box.",
    location: "Abuja, Nigeria",
    dateListed: "May 5, 2025",
    datePosted: "May 5, 2025",
    edited: "May 5, 2025",
    requestedInExchange: [{ name: "iPhone 15 Pro" }],
    owner: "Michael Adeyemi",
    ownerAvatar: "https://example.com/images/avatar2.png",
    rating: 4.7,
    swap: { total: 7 },
  },
  {
    name: "Flagged for Review",
    date: "2025-07-19T09:20:00Z",
    item: "MacBook Pro 2023",
    condition: "Used",
    price: 2000,
    itemUrl: "https://example.com/images/macbookpro2023.png",
    category: "Computers",
    status: "Flagged",
    description: "MacBook Pro 2023, 16-inch, M2 Max, minor scratches.",
    location: "Port Harcourt, Nigeria",
    dateListed: "May 5, 2025",
    datePosted: "May 5, 2025",
    edited: "May 5, 2025",
    requestedInExchange: [{ name: "Surface Laptop Studio" }],
    owner: "Amaka Okoro",
    ownerAvatar: "https://example.com/images/avatar3.png",
    rating: 4.5,
    swap: { total: 5 },
  },
  {
    name: "Active Trade Ongoing",
    date: "2025-07-18T12:10:00Z",
    item: "PlayStation 5",
    condition: "Like New",
    price: 600,
    itemUrl: "https://example.com/images/ps5.png",
    category: "Gaming",
    status: "Active",
    description: "PlayStation 5, barely used, comes with 2 controllers.",
    location: "Ibadan, Nigeria",
    dateListed: "May 5, 2025",
    datePosted: "May 5, 2025",
    edited: "May 5, 2025",
    requestedInExchange: [{ name: "Xbox Series X" }],
    owner: "James Oladipo",
    ownerAvatar: "https://example.com/images/avatar4.png",
    rating: 4.6,
    swap: { total: 8 },
  },
  {
    name: "Completed Swap Transaction",
    date: "2025-07-17T18:55:00Z",
    item: "Canon EOS R5 Camera",
    condition: "Excellent",
    price: 2500,
    itemUrl: "https://example.com/images/canonr5.png",
    category: "Cameras",
    status: "Completed",
    description: "Canon EOS R5, excellent condition, includes 24-70mm lens.",
    location: "Enugu, Nigeria",
    dateListed: "May 5, 2025",
    datePosted: "May 5, 2025",
    edited: "May 5, 2025",
    requestedInExchange: [{ name: "Sony A7 IV" }],
    owner: "Chidinma Bello",
    ownerAvatar: "https://example.com/images/avatar5.png",
    rating: 4.8,
    swap: { total: 6 },
  },
];
